name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create auth credentials file
        run: |
          mkdir -p cypress/fixtures
          cat > cypress/fixtures/auth-credentials.json << EOF
          {
            "admin": {
              "username": "${{ secrets.ADMIN_USERNAME }}",
              "password": "${{ secrets.ADMIN_PASSWORD }}",
              "email": "${{ secrets.ADMIN_EMAIL }}"
            },
            "user": {
              "username": "${{ secrets.USER_USERNAME }}",
              "password": "${{ secrets.USER_PASSWORD }}",
              "email": "${{ secrets.USER_EMAIL }}"
            },
            "tokens": {
              "adminToken": "${{ secrets.ADMIN_TOKEN }}",
              "userToken": "${{ secrets.USER_TOKEN }}"
            }
          }
          EOF
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: false
          spec: "cypress/e2e/**/*.cy.js"
      
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos