name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]  # Extra bracket removed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create auth credentials file
        run: |
          mkdir -p cypress/fixtures
          cat > cypress/fixtures/auth-credentials.json << EOF
          {
            "admin": {
              "username": "${{ secrets.ADMIN_USERNAME }}",
              "password": "${{ secrets.ADMIN_PASSWORD }}",
              "email": "${{ secrets.ADMIN_EMAIL }}"
            },
            "user": {
              "username": "${{ secrets.USER_USERNAME }}",
              "password": "${{ secrets.USER_PASSWORD }}",
              "email": "${{ secrets.USER_EMAIL }}"
            },
            "tokens": {
              "adminToken": "${{ secrets.ADMIN_TOKEN }}",
              "userToken": "${{ secrets.USER_TOKEN }}"
            }
          }
          EOF
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          record: true        # You need a Cypress Dashboard account for this
          parallel: true      # Enable parallelization
          group: UI-Tests     # Name of the test group (hyphens instead of spaces)
          ci-build-id: ${{ github.run_id }}-${{ github.run_attempt }}
          spec: "cypress/e2e/**/*.cy.js"
        env:
          # Pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Pass Cypress Dashboard record key
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report-${{ matrix.containers }}
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos