name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - website
          - crm
          - component

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define test suites based on input or default to all
        test_suite: ${{ fromJSON(github.event.inputs.test_type == 'all' && '["website", "crm", "component"]' || format('["{}"]', github.event.inputs.test_type || 'all')) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './areti-test-suite/package-lock.json'
      
      - name: Install Dependencies
        run: cd areti-test-suite && npm ci
      
      - name: Create cypress.env.json
        run: |
          echo '{
            "AUTH_USERNAME": "${{ secrets.AUTH_USERNAME }}",
            "AUTH_PASSWORD": "${{ secrets.AUTH_PASSWORD }}",
            "AUTH_TOKEN": "${{ secrets.AUTH_TOKEN }}"
          }' > ./areti-test-suite/cypress.env.json
      
      # Run website E2E tests
      - name: Run Website Tests
        if: matrix.test_suite == 'website' || matrix.test_suite == 'all'
        uses: cypress-io/github-action@v6
        with:
          working-directory: areti-test-suite
          command: npm run test:website
      
      # Run CRM E2E tests
      - name: Run CRM Tests
        if: matrix.test_suite == 'crm' || matrix.test_suite == 'all'
        uses: cypress-io/github-action@v6
        with:
          working-directory: areti-test-suite
          command: npm run test:crm
      
      # Run component tests
      - name: Run Component Tests
        if: matrix.test_suite == 'component' || matrix.test_suite == 'all'
        uses: cypress-io/github-action@v6
        with:
          working-directory: areti-test-suite
          command: npm run test:component:website && npm run test:component:crm
      
      # Upload artifacts on failure
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.test_suite }}
          path: areti-test-suite/cypress/screenshots
          if-no-files-found: ignore
      
      - name: Upload Videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-${{ matrix.test_suite }}
          path: areti-test-suite/cypress/videos
          if-no-files-found: ignore